name: Discord Commit Details
on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Format commit message
        id: format-commit
        run: |
          SHORT_HASH=$(git log -1 --pretty=%h)
          AUTHOR=$(git log -1 --pretty=%an)
          MESSAGE=$(git log -1 --pretty=%s)
          BODY=$(git log -1 --pretty=%b | sed '/^$/d' | sed 's/^/- /' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          echo "MESSAGE<<EOF" >> $GITHUB_ENV
          echo "🔹 **$MESSAGE**" >> $GITHUB_ENV
          echo "🔸 Автор: $AUTHOR" >> $GITHUB_ENV
          echo "🔸 Ветка: ${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "**Изменения:**" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: ${{ env.MESSAGE }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}